# Generated by Django 3.1.2 on 2020-11-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maidelderlycare',
            name='maid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elderly_care', to='maid.maid'),
        ),
    ]
