# Generated by Django 3.1.2 on 2020-11-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maid',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
