# Generated by Django 3.1.4 on 2020-12-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maid',
            old_name='repatraition_airport',
            new_name='repatriation_airport',
        ),
        migrations.RenameField(
            model_name='maidstatus',
            old_name='ipa_arroved',
            new_name='ipa_approved',
        ),
    ]
