# Generated by Django 3.1.4 on 2020-12-23 02:32

from django.db import migrations, models
import onlinemaid.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0002_auto_20201222_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='maid',
            name='photo',
            field=models.FileField(null=True, storage=onlinemaid.storage_backends.PublicMediaStorage(), upload_to='', verbose_name='Maid Photo'),
        ),
        migrations.AlterField(
            model_name='maid',
            name='repatriation_airport',
            field=models.CharField(max_length=100, verbose_name='Repatriation airport'),
        ),
    ]
