# Generated by Django 3.1.2 on 2020-11-26 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0002_auto_20201125_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='maid',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
