# Generated by Django 3.1.2 on 2020-11-26 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0003_maid_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maid',
            old_name='eldery_care_complete',
            new_name='elderly_care_complete',
        ),
    ]
