# Generated by Django 3.1.2 on 2020-11-02 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0004_auto_20201102_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maidbiodata',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='maidbiodata',
            name='last_name',
        ),
        migrations.AddField(
            model_name='maidbiodata',
            name='name',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
