# Generated by Django 3.1.2 on 2020-11-26 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0004_auto_20201126_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maid',
            name='status_complete',
        ),
    ]
