# Generated by Django 3.1.2 on 2020-11-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0006_auto_20201102_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='maidbiodata',
            name='age',
            field=models.IntegerField(null=True, verbose_name='Age'),
        ),
    ]
