# Generated by Django 3.1.2 on 2020-11-07 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maid', '0007_maidbiodata_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='maid',
            name='status_complete',
            field=models.BooleanField(blank=True, default=False, editable=False),
        ),
        migrations.CreateModel(
            name='MaidStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipa_arroved', models.BooleanField(default=False, verbose_name='IPA approved')),
                ('bond_date', models.DateField(null=True, verbose_name='Bond Date')),
                ('sip_date', models.DateField(null=True, verbose_name='SIP Date')),
                ('thumbprint_date', models.DateField(null=True, verbose_name='Thumbprint Date')),
                ('deployment_date', models.DateField(null=True, verbose_name='Deployment Date')),
                ('maid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='maid.maid')),
            ],
        ),
    ]
