# Generated by Django 3.1.2 on 2020-11-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('E', 'Employer'), ('A', 'Agency'), ('AA', 'Agency Administrator'), ('AE', 'Agency Employee')], default='E', max_length=2, verbose_name='Role'),
        ),
    ]
