# Generated by Django 3.1.2 on 2020-11-02 05:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('E', 'Employer'), ('A', 'Agency'), ('AE', 'Agency Employee')], default='E', max_length=2, verbose_name='Role'),
        ),
    ]
