# Generated by Django 3.1.2 on 2020-11-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201119_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('E', 'Employer'), ('AO', 'Agency Owner'), ('AA', 'Agency Administrator'), ('AM', 'Agency Manager'), ('AE', 'Agency Employee')], default='E', max_length=2, verbose_name='Role'),
        ),
    ]
