# Generated by Django 3.1.2 on 2020-11-10 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Page name')),
                ('tier', models.CharField(choices=[('NONE', 'None'), ('TIER1', 'Tier 1'), ('TIER2', 'Tier 2'), ('TIER3', 'Tier 3')], default='NONE', max_length=5, verbose_name='Advertisment tier')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('NONE', 'None'), ('BANNER', 'Banner'), ('TESTI', 'Testimonial')], default='NONE', max_length=6, verbose_name='Advertisment type')),
                ('start_date', models.DateTimeField(editable=False, null=True, verbose_name='Advertisment end date')),
                ('approved', models.BooleanField(default=False, editable=False, verbose_name='Approved')),
                ('paid', models.BooleanField(default=False, editable=False, verbose_name='Paid')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='agency.agency')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='advertisement.advertisementlocation')),
            ],
        ),
    ]
