# Generated by Django 3.1.2 on 2020-11-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='ad_type',
            field=models.CharField(choices=[('NONE', 'None'), ('BANNER', 'Banner'), ('TESTI', 'Testimonial')], default='NONE', max_length=6, verbose_name='Advertisment type'),
        ),
        migrations.AlterField(
            model_name='advertisementlocation',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Page name'),
        ),
        migrations.AlterField(
            model_name='advertisementlocation',
            name='tier',
            field=models.CharField(choices=[('NONE', 'None'), ('TIER1', 'Tier 1'), ('TIER2', 'Tier 2'), ('TIER3', 'Tier 3')], default='NONE', max_length=5, verbose_name='Advertisment tier'),
        ),
    ]
