# Generated by Django 3.1.4 on 2020-12-24 10:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('contact_number', models.CharField(max_length=100, verbose_name='Contact Number')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('property_type', models.CharField(choices=[('2RMHDB', '2-Room HDB'), ('3RMHDB', '3-Room HDB'), ('4RMHDB', '4-Room HDB'), ('5RMHDB', '5-Room HDB'), ('E/MHDB', 'Executive/Maisonette HDB'), ('CONDO', 'Condominium'), ('CONDOP', 'Condominium Penthouse'), ('TERRACE', 'Terrace'), ('SEMI-D', 'Semi-Detached'), ('BUNGLO', 'Bungalow'), ('OTH', 'Others')], max_length=7, verbose_name='Type of Property')),
                ('maid_nationality', models.CharField(choices=[('ALL', 'No preference'), ('KHM', 'Cambodian'), ('PHL', 'Filipino'), ('IND', 'Indian'), ('IDN', 'Indonesian'), ('MMR', 'Myanmarese'), ('LKA', 'Sri Lankan'), ('OTH', 'Others')], max_length=3, verbose_name="Maid's Nationality")),
                ('maid_responsibility', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('ALL', 'No preference'), ('GEH', 'General Housework'), ('COK', 'Cooking'), ('CFI', 'Care for Infants/Children'), ('CFE', 'Care for the Elderly'), ('CFD', 'Care for the Disabled'), ('CFP', 'Care for Pets'), ('GAR', 'Gardening')], max_length=3, verbose_name="Maid's main responsibility"), size=None)),
                ('maid_type', models.CharField(choices=[('ALL', 'No preference'), ('NEW', 'No Experience'), ('TRA', 'Transfer'), ('SGE', 'Singapore Experience'), ('OVE', 'Overseas Experience')], max_length=3, verbose_name='Type of maid')),
                ('maid_age_group', models.CharField(choices=[('23-29', '23-29'), ('30-39', '30-39'), ('40-49', '40-49'), ('above 50', 'Above 50')], max_length=8, verbose_name='Maid Age Group')),
                ('rest_days', models.CharField(choices=[('0RD', '0 Rest Days Per Month'), ('1RD', '1 Rest Days Per Month'), ('2RD', '2 Rest Days Per Month'), ('3RD', '3 Rest Days Per Month'), ('4RD', '4 Rest Days Per Month')], max_length=3, verbose_name='Number of Rest Days')),
                ('no_of_family_members', models.IntegerField(verbose_name='Number of Family Members')),
                ('no_of_below_12', models.IntegerField(verbose_name='Number of Children below 12')),
                ('no_of_babies', models.IntegerField(verbose_name='Number of Babies')),
                ('remarks', models.TextField(verbose_name='Remarks')),
            ],
        ),
    ]
