# Generated by Django 3.1.4 on 2020-12-08 10:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employer_documentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerbase',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
