# Generated by Django 3.1.4 on 2020-12-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_documentation', '0002_auto_20201208_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerdocsig',
            name='agency_staff_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerdocsig',
            name='employer_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerdocsig',
            name='fdw_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerdocsig',
            name='sponsor_signature',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employerdocsig',
            name='spouse_signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
