# Generated by Django 3.1.4 on 2020-12-17 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employer_documentation', '0003_auto_20201215_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerdocserviceagreement',
            name='c4_1_replacement_after_min_working_days',
            field=models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')], default=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employerdocsig',
            name='employer_doc_base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rn_docsignatures', to='employer_documentation.employerdocbase'),
        ),
    ]
