# Generated by Django 3.1.4 on 2020-12-18 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_documentation', '0006_auto_20201218_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='employerdocjoborder',
            name='job_order_date_1',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
