# Generated by Django 3.1.4 on 2020-12-21 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_documentation', '0007_employerdocjoborder_job_order_date_1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employerdocmaidstatus',
            name='date_of_application_for_transfer',
        ),
        migrations.AddField(
            model_name='employerdocmaidstatus',
            name='work_permit_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
