# Generated by Django 3.1.4 on 2020-12-24 08:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
        ('maid', '0001_initial'),
        ('employer_documentation', '0008_auto_20201221_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('employer_name', models.CharField(max_length=40)),
                ('employer_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('employer_mobile_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Mobile Number')),
                ('employer_nric', models.CharField(max_length=20)),
                ('employer_address_1', models.CharField(max_length=100, null=True, verbose_name='Street Address')),
                ('employer_address_2', models.CharField(max_length=50, null=True, verbose_name='Unit Number')),
                ('employer_postal_code', models.CharField(max_length=25, null=True, verbose_name='Postal Code')),
                ('agency_employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='agency.agencyemployee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerDoc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('case_ref_no', models.CharField(max_length=20, unique=True)),
                ('spouse_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('sponsor_required', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('b1_service_fee', models.PositiveIntegerField()),
                ('b2a_work_permit_application_collection', models.PositiveIntegerField()),
                ('b2b_medical_examination_fee', models.PositiveIntegerField()),
                ('b2c_security_bond_accident_insurance', models.PositiveIntegerField()),
                ('b2d_indemnity_policy_reimbursement', models.PositiveIntegerField()),
                ('b2e_home_service', models.PositiveIntegerField()),
                ('b2f_counselling', models.PositiveIntegerField()),
                ('b2g_sip', models.PositiveIntegerField()),
                ('b2h_replacement_months', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')])),
                ('b2h_replacement_cost', models.PositiveIntegerField()),
                ('b2i_work_permit_renewal', models.PositiveIntegerField()),
                ('b2j1_other_services_description', models.CharField(blank=True, max_length=40, null=True)),
                ('b2j1_other_services_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('b2j2_other_services_description', models.CharField(blank=True, max_length=40, null=True)),
                ('b2j2_other_services_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('b2j3_other_services_description', models.CharField(blank=True, max_length=40, null=True)),
                ('b2j3_other_services_fee', models.PositiveIntegerField(blank=True, null=True)),
                ('ca_deposit', models.PositiveIntegerField()),
                ('fdw_is_replacement', models.BooleanField()),
                ('b4_loan_transferred', models.PositiveIntegerField(blank=True, null=True)),
                ('c1_3_handover_days', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')])),
                ('c3_2_no_replacement_criteria_1', models.CharField(max_length=100)),
                ('c3_2_no_replacement_criteria_2', models.CharField(max_length=100)),
                ('c3_2_no_replacement_criteria_3', models.CharField(max_length=100)),
                ('c3_4_no_replacement_refund', models.PositiveIntegerField()),
                ('c4_1_number_of_replacements', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')])),
                ('c4_1_replacement_period', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')])),
                ('c4_1_replacement_after_min_working_days', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')])),
                ('c4_1_5_replacement_deadline', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24')])),
                ('c5_1_1_deployment_deadline', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')])),
                ('c5_1_1_failed_deployment_refund', models.PositiveIntegerField()),
                ('c5_1_2_refund_within_days', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')])),
                ('c5_1_2_before_fdw_arrives_charge', models.PositiveIntegerField()),
                ('c5_1_2_after_fdw_arrives_charge', models.PositiveIntegerField()),
                ('c5_2_2_can_transfer_refund_within', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('c5_3_2_cannot_transfer_refund_within', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')])),
                ('c6_4_per_day_food_accommodation_cost', models.PositiveSmallIntegerField()),
                ('c6_6_per_session_counselling_cost', models.PositiveIntegerField()),
                ('c9_1_independent_mediator_1', models.CharField(max_length=40)),
                ('c9_2_independent_mediator_2', models.CharField(max_length=40)),
                ('c13_termination_notice', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')])),
                ('c3_2_salary_payment_date', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28')])),
                ('c3_5_fdw_sleeping_arrangement', models.CharField(choices=[('Have own room', 'Have own room'), ('Sharing room with someone', 'Sharing room with someone'), ('Sleeping in common area', 'Sleeping in common area')], max_length=40)),
                ('c4_1_termination_notice', models.PositiveSmallIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30')])),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='rn_ed_employer', to='employer_documentation.employer')),
                ('fdw', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='maid.maid')),
                ('fdw_replaced', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='rn_ed_fdwreplaced', to='maid.maid')),
            ],
        ),
        migrations.RemoveField(
            model_name='employerdocbase',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='employerdocbase',
            name='fdw',
        ),
        migrations.RemoveField(
            model_name='employerdocemploymentcontract',
            name='employer_doc_base',
        ),
        migrations.RemoveField(
            model_name='employerdocjoborder',
            name='employer_doc_base',
        ),
        migrations.RemoveField(
            model_name='employerdocserviceagreement',
            name='employer_doc_base',
        ),
        migrations.RemoveField(
            model_name='employerdocservicefeebase',
            name='employer_doc_base',
        ),
        migrations.RemoveField(
            model_name='employerdocservicefeereplacement',
            name='fdw_replaced',
        ),
        migrations.RemoveField(
            model_name='employerdocservicefeereplacement',
            name='service_fee_schedule',
        ),
        migrations.RemoveField(
            model_name='employerextrainfo',
            name='employer_base',
        ),
        migrations.RemoveField(
            model_name='employerdocmaidstatus',
            name='employer_doc_base',
        ),
        migrations.RemoveField(
            model_name='employerdocsig',
            name='employer_doc_base',
        ),
        migrations.DeleteModel(
            name='EmployerBase',
        ),
        migrations.DeleteModel(
            name='EmployerDocBase',
        ),
        migrations.DeleteModel(
            name='EmployerDocEmploymentContract',
        ),
        migrations.DeleteModel(
            name='EmployerDocJobOrder',
        ),
        migrations.DeleteModel(
            name='EmployerDocServiceAgreement',
        ),
        migrations.DeleteModel(
            name='EmployerDocServiceFeeBase',
        ),
        migrations.DeleteModel(
            name='EmployerDocServiceFeeReplacement',
        ),
        migrations.DeleteModel(
            name='EmployerExtraInfo',
        ),
        migrations.AddField(
            model_name='employerdocmaidstatus',
            name='employer_doc',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rn_maidstatus_ed', to='employer_documentation.employerdoc'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employerdocsig',
            name='employer_doc',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='rn_signatures_ed', to='employer_documentation.employerdoc'),
            preserve_default=False,
        ),
    ]
