# Generated by Django 3.1.4 on 2020-12-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_documentation', '0009_auto_20201224_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='employer_postal_code',
        ),
        migrations.AddField(
            model_name='employer',
            name='employer_post_code',
            field=models.CharField(max_length=25, null=True, verbose_name='Post Code'),
        ),
    ]
