# Generated by Django 3.1.4 on 2020-12-24 10:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer_documentation', '0010_auto_20201224_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='employer_address_1',
            field=models.CharField(default=None, max_length=100, verbose_name='Street Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='employer_address_2',
            field=models.CharField(default=None, max_length=50, verbose_name='Unit Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='employer_mobile_number',
            field=models.CharField(default=None, max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Mobile Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employer',
            name='employer_post_code',
            field=models.CharField(default=None, max_length=25, verbose_name='Post Code'),
            preserve_default=False,
        ),
    ]
