# Generated by Django 3.1.2 on 2020-10-29 15:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertisementLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30, verbose_name='Page name')),
                ('tier', models.TextField(choices=[('NONE', 'None'), ('TIER1', 'Tier 1'), ('TIER2', 'Tier 2'), ('TIER3', 'Tier 3')], default='NONE', max_length=5, verbose_name='Advertisment tier')),
            ],
        ),
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('company_email', models.EmailField(max_length=254)),
                ('name', models.TextField(max_length=100, verbose_name='Name')),
                ('license_number', models.TextField(max_length=100, verbose_name='License number')),
                ('website_uri', models.TextField(max_length=100, validators=[django.core.validators.URLValidator(message='Please enter a valid URL')], verbose_name='Website URL')),
                ('uen', models.TextField(max_length=10, verbose_name="Company's UEN code")),
                ('active', models.BooleanField(default=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyContactInformation',
            fields=[
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agency.agency')),
                ('office_number', models.TextField(max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Office Number')),
                ('mobile_number', models.TextField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Mobile Number')),
                ('sales_email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyLocation',
            fields=[
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agency.agency')),
                ('address_1', models.TextField(max_length=100, verbose_name='Street Address')),
                ('address_2', models.TextField(max_length=50, verbose_name='Unit Number')),
                ('postal_code', models.TextField(max_length=25, verbose_name='Postal Code')),
                ('area', models.TextField(choices=[('C', 'Central'), ('N', 'North'), ('NE', 'North East'), ('E', 'East'), ('W', 'West')], default='C', max_length=2, verbose_name='Area')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyOperatingHours',
            fields=[
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agency.agency')),
                ('operating_type', models.TextField(choices=[('OH', 'Opening Hours'), ('AO', 'Appointment Only')], default='OH', max_length=2, verbose_name="Agency's operating hours type")),
                ('monday', models.TextField(blank=True, max_length=30, verbose_name="Monday's opening hours")),
                ('tuesday', models.TextField(blank=True, max_length=30, verbose_name="Tuesday's opening hours")),
                ('wednesday', models.TextField(blank=True, max_length=30, verbose_name="Wednesday's opening hours")),
                ('thursday', models.TextField(blank=True, max_length=30, verbose_name="Thursday's opening hours")),
                ('friday', models.TextField(blank=True, max_length=30, verbose_name="Friday's opening hours")),
                ('saturday', models.TextField(blank=True, max_length=30, verbose_name="Saturday's opening hours")),
                ('sunday', models.TextField(blank=True, max_length=30, verbose_name="Sunday's opening hours")),
                ('public_holiday', models.TextField(blank=True, max_length=30, verbose_name='Public holiday opening hours')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyPlan',
            fields=[
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='agency.agency')),
                ('choice', models.TextField(choices=[('B100', '100 Biodata'), ('B200', '200 Biodata'), ('B300', '300 Biodata')], default='B100', max_length=4, verbose_name='Plan type')),
                ('expiry_date', models.DateTimeField(editable=False, verbose_name='Plan expiry date')),
                ('remarks', models.TextField(blank=True, max_length=100, verbose_name='Remarks')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyEmployee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('first_name', models.TextField(max_length=50, verbose_name='First Name')),
                ('last_name', models.TextField(max_length=50, verbose_name='Last Name')),
                ('contact_number', models.TextField(max_length=50, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Contact Number')),
                ('ea_personnel_number', models.TextField(max_length=50, verbose_name='EA personnel number')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='agency.agency')),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.TextField(choices=[('NONE', 'None'), ('BANNER', 'Banner'), ('TESTI', 'Testimonial')], default='NONE', max_length=6, verbose_name='Advertisment type')),
                ('start_date', models.DateTimeField(editable=False, verbose_name='Advertisment end date')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='agency.agency')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='agency.advertisementlocation')),
            ],
        ),
    ]
