# Generated by Django 3.1.4 on 2020-12-08 09:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_email', models.EmailField(max_length=254, verbose_name='Company Email Address')),
                ('sales_email', models.EmailField(max_length=254, verbose_name='Company Sales Email Address')),
                ('name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('license_number', models.CharField(max_length=100, verbose_name='License number')),
                ('website_uri', models.CharField(max_length=100, validators=[django.core.validators.URLValidator(message='Please enter a valid URL')], verbose_name='Website URL')),
                ('uen', models.CharField(max_length=10, verbose_name="Company's UEN code")),
                ('active', models.BooleanField(default=True, editable=False)),
                ('complete', models.BooleanField(default=False, editable=False)),
                ('branch_complete', models.BooleanField(default=False, editable=False)),
                ('operating_hours_complete', models.BooleanField(default=False, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='AgencyBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Branch Name')),
                ('address_1', models.CharField(max_length=100, null=True, verbose_name='Street Address')),
                ('address_2', models.CharField(max_length=50, null=True, verbose_name='Unit Number')),
                ('postal_code', models.CharField(max_length=25, null=True, verbose_name='Postal Code')),
                ('area', models.CharField(choices=[('C', 'Central'), ('N', 'North'), ('NE', 'North East'), ('E', 'East'), ('W', 'West')], default='C', max_length=2, verbose_name='Area')),
                ('office_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Office Number')),
                ('mobile_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Mobile Number')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='agency.agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyOperatingHours',
            fields=[
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='operating_hours', serialize=False, to='agency.agency')),
                ('operating_type', models.CharField(choices=[('OH', 'Opening Hours'), ('AO', 'Appointment Only')], default='OH', max_length=2, verbose_name="Agency's operating hours type")),
                ('monday', models.CharField(blank=True, max_length=30, verbose_name="Monday's opening hours")),
                ('tuesday', models.CharField(blank=True, max_length=30, verbose_name="Tuesday's opening hours")),
                ('wednesday', models.CharField(blank=True, max_length=30, verbose_name="Wednesday's opening hours")),
                ('thursday', models.CharField(blank=True, max_length=30, verbose_name="Thursday's opening hours")),
                ('friday', models.CharField(blank=True, max_length=30, verbose_name="Friday's opening hours")),
                ('saturday', models.CharField(blank=True, max_length=30, verbose_name="Saturday's opening hours")),
                ('sunday', models.CharField(blank=True, max_length=30, verbose_name="Sunday's opening hours")),
                ('public_holiday', models.CharField(blank=True, max_length=30, verbose_name='Public holiday opening hours')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('B100', '100 Biodata'), ('B200', '200 Biodata'), ('B300', '300 Biodata')], default='B100', max_length=4, verbose_name='Plan type')),
                ('expiry_date', models.DateTimeField(editable=False, verbose_name='Plan expiry date')),
                ('remarks', models.CharField(blank=True, max_length=100, verbose_name='Remarks')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agency_owner', serialize=False, to='accounts.user')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='agency.agency')),
            ],
        ),
        migrations.CreateModel(
            name='AgencyEmployee',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agency_employee', serialize=False, to='accounts.user')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contact_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Contact Number')),
                ('ea_personnel_number', models.CharField(max_length=50, verbose_name='EA personnel number')),
                ('role', models.CharField(choices=[('AA', 'Administrator'), ('AM', 'Manager'), ('AS', 'Sales Staff')], default='AS', max_length=2, verbose_name='Employee Role')),
                ('deleted', models.BooleanField(default=False, editable=False)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='agency.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='agency.agencybranch')),
            ],
        ),
    ]
