# Generated by Django 3.1.2 on 2020-11-02 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.DeleteModel(
            name='AdvertisementLocation',
        ),
    ]
