# Generated by Django 3.1.2 on 2020-11-19 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201119_1159'),
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='user',
        ),
        migrations.AddField(
            model_name='agency',
            name='id',
            field=models.AutoField(auto_created=True, default=None, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencyoperatinghours',
            name='agency',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='operating_hours', serialize=False, to='agency.agency'),
        ),
        migrations.CreateModel(
            name='AgencyOwner',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='agency.agency')),
            ],
        ),
    ]
