# Generated by Django 3.1.2 on 2020-11-19 12:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201119_1159'),
        ('agency', '0002_auto_20201119_1159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencyemployee',
            name='role',
        ),
        migrations.CreateModel(
            name='AgencyManager',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contact_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Contact Number')),
                ('ea_personnel_number', models.CharField(max_length=50, verbose_name='EA personnel number')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='agency.agency')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='agency.agencybranch')),
            ],
        ),
    ]
