# Generated by Django 3.1.2 on 2020-11-07 15:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20201102_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Branch Name')),
                ('address_1', models.CharField(max_length=100, null=True, verbose_name='Street Address')),
                ('address_2', models.CharField(max_length=50, null=True, verbose_name='Unit Number')),
                ('postal_code', models.CharField(max_length=25, null=True, verbose_name='Postal Code')),
                ('area', models.CharField(choices=[('C', 'Central'), ('N', 'North'), ('NE', 'North East'), ('E', 'East'), ('W', 'West')], default='C', max_length=2, verbose_name='Area')),
                ('office_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Office Number')),
                ('mobile_number', models.CharField(max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Mobile Number')),
            ],
        ),
        migrations.RemoveField(
            model_name='agencylocation',
            name='agency',
        ),
        migrations.RenameField(
            model_name='agency',
            old_name='contact_information_complete',
            new_name='branch_complete',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='location_complete',
        ),
        migrations.AddField(
            model_name='agency',
            name='sales_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='role',
            field=models.CharField(choices=[('M', 'Manager'), ('S', 'Sales staff')], default='S', max_length=1, verbose_name="Employee's Role"),
        ),
        migrations.AlterField(
            model_name='agency',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Company Name'),
        ),
        migrations.DeleteModel(
            name='AgencyContactInformation',
        ),
        migrations.DeleteModel(
            name='AgencyLocation',
        ),
        migrations.AddField(
            model_name='agencybranch',
            name='agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='agency.agency'),
        ),
    ]
