# Generated by Django 3.1.2 on 2020-11-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_auto_20201119_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agencymanager',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='agencymanager',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='agencymanager',
            name='user',
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='agencyemployee',
            name='role',
            field=models.CharField(choices=[('AA', 'Administrator'), ('AM', 'Manager'), ('AS', 'Sales Staff')], default='AS', max_length=2, verbose_name='Employee Role'),
        ),
        migrations.DeleteModel(
            name='AgencyAdministrator',
        ),
        migrations.DeleteModel(
            name='AgencyManager',
        ),
    ]
