# Generated by Django 3.1.2 on 2020-11-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_auto_20201107_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='company_email',
            field=models.EmailField(max_length=254, verbose_name='Company Email Address'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='sales_email',
            field=models.EmailField(max_length=254, verbose_name='Company Sales Email Address'),
        ),
    ]
