# Generated by Django 3.1.2 on 2020-11-21 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agency', '0004_auto_20201120_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyemployee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agency_employee', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='agencyowner',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='agency_owner', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
