# Generated by Django 3.1.2 on 2020-11-09 14:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201102_0517'),
        ('agency', '0006_auto_20201107_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyemployee',
            name='branch',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='agency.agencybranch'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agencyemployee',
            name='role',
            field=models.CharField(choices=[('M', 'Manager'), ('S', 'Sales staff')], default='S', max_length=1, verbose_name="Employee's Role"),
        ),
        migrations.CreateModel(
            name='AgencyAdministrator',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('contact_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Please enter a valid contact number', regex='^[0-9]*$')], verbose_name='Contact Number')),
                ('ea_personnel_number', models.CharField(max_length=50, verbose_name='EA personnel number')),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='agency.agency')),
            ],
        ),
    ]
